---
  - name: Install Grafana
    hosts: monitor

    tasks:
    - name: Install Grafana on Ubuntu using installpackageubuntu role
      include_role:
        name: installpackageubuntu
      vars:
        url: "https://packages.grafana.com/gpg.key"
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        package: "grafana"
        service: "grafana-server"
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: Stop Firewall on Ubuntu using stopfirewallubuntu role
      include_role:
        name: stopfirewallubuntu
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Grafana on CentOS using installpackagecentos role
      include_role:
        name: installpackagecentos
      vars:
        src: grafana.repo-centos
        dest: "/etc/yum.repos.d/grafana.repo"
        package: grafana
        service: grafana-server
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Stop Firewall on CentOS using stopfirewallcentos role
      include_role:
        name: stopfirewallcentos
      when: ansible_facts['os_family'] == 'RedHat'


  - name: Install Telegraf
    hosts: monitor

    tasks:
    - name: Install Telegraf dependencies on Ubuntu using installpackageubuntu role
      include_role:
        name: installpackageubuntu
      vars:
        url: ""
        repo: ""
        package: gnupg2
        service: ""
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Telegraf dependencies on Ubuntu using installpackageubuntu role
      include_role:
        name: installpackageubuntu
      vars:
        url: ""
        repo: ""
        package: software-properties-common
        service: ""
      when: ansible_facts['os_family'] == 'Debian' 

    - name: Install InfluxDB on Ubuntu using installpackageubuntu role
      include_role:
        name: installpackageubuntu
      vars:
        url: "https://repos.influxdata.com/influxdb.key"
        repo: "deb https://repos.influxdata.com/ubuntu bionic stable"
        package: influxdb
        service: influxdb
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Telegraf on Ubuntu using installpackageubuntu role
      include_role:
        name: installpackageubuntu
      vars:
        url: ""
        repo: ""
        package: telegraf
        service: telegraf
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: Stop Firewall on Ubuntu using stopfirewallubuntu role
      include_role:
        name: stopfirewallubuntu
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install InfluxDB on CentOS using installpackagecentos role
      include_role:
        name: installpackagecentos
      vars:
        src: influxdb.repo-centos
        dest: /etc/yum.repos.d/influxdb.repo
        package: influxdb
        service: influxdb
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install Telegraf on CentOS using installpackagecentos role
      include_role:
        name: installpackagecentos
      vars:
        src: ""
        dest: ""
        package: telegraf
        service: telegraf
      when: ansible_facts['os_family'] == 'RedHat'
  
    - name: Stop Firewall on CentOS using stopfirewallcentos role
      include_role:
        name: stopfirewallcentos
      when: ansible_facts['os_family'] == 'RedHat'


  - name: Install Prometheus
    hosts: monitor

    tasks:
    - name: Install Prometheus on Ubuntu using installprometheusubuntu role
      include_role:
        name: installprometheusubuntu
      vars:
        src: prometheus.service
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: Stop Firewall on Ubuntu using stopfirewallubuntu role
      include_role:
        name: stopfirewallubuntu
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Prometheus on CentOS using installprometeuscentos role
      include_role:
        name: installprometheuscentos
      vars:
        src: prometheus.service
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Stop Firewall on CentOS using stopfirewallcentos role
      include_role:
        name: stopfirewallcentos
      when: ansible_facts['os_family'] == 'RedHat'
